services:
  - type: web
    name: discord-bot
    env: docker
    buildCommand: docker build -t discord-bot .
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
